<?php

namespace RatingBundle\Repositories;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userID
     * @return array
     */
    public function calculateUserAverageRating($userID)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT AVG(r.rating) as avg_rate FROM RatingBundle:Review r WHERE r.user = :user_id'
            )
            ->setParameter('user_id', $userID)
            ->getSingleScalarResult();
    }
}
