services:

    user_repository:
        class: RatingBundle\Repositories\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - RatingBundle\Entity\User