services:
#    user_repository:
#        class: RatingBundle\Repositories\UserRepository
#        factory_service: doctrine
#        factory_method: getRepository
#        arguments:
#          - RatingBundle:User